### PR TITLE
updated deps

### PR DESCRIPTION
**Pull request by lenw**

### CODE REVIEW

**Review by aterreno — APPROVED** [review]

**Comment by aterreno** [comment]
Thanks @lenw - Not updating or using this library for a while now, if you want to help with publishing it to clojar that'd be awesome - I guess a build on travis would do the trick.

**Comment by lenw** [comment]
@aterreno sorry to bug - happy to do it just dont know how ?

**Comment by lenw** [comment]
@aterreno I have registered on clojars and am attempting the deploy - looks like I need access to the clojars group 

> Could not transfer artifact etcd-clojure:etcd-clojure:jar:0.2.5 from/to clojars (https://clojars.org/repo/): Access denied to: https://clojars.org/repo/etcd-clojure/etcd-clojure/0.2.5/etcd-clojure-0.2.5.jar, ReasonPhrase: Forbidden - You don't have access to the 'etcd-clojure' group.

**Comment by aterreno** [comment]
Good stuff, what's your user id there? Same as on github? @lenw

**Comment by lenw** [comment]
Is just @len on clojars

**Comment by aterreno** [comment]
Cool Try now

**Comment by lenw** [comment]
Perfect - updated to 0.2.5
Thanks

**Comment by aterreno** [comment]
Thanks to you!

**Pull request merged**
